airflow-helm/charts

charts/airflow/Chart.yaml
charts/airflow/templates/config/secret-connections.yaml

- fixes #14
Resolves issue where bash sees `$` as environment variables in connection strings.

fix quoting of "$" in connections

---

charts/airflow/Chart.yaml
charts/airflow/README.md
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/values.yaml

Signed-off-by: lidor ettinger <lidor.ettinger@gmail.com>
In the same way as we can add secrets for web and workers we would like to do also for scheduler.
This PR provides a way to add a credential for a local repository, such as nexus, in order to download its dependencies.

scheduler kubernetes secrets

---

charts/airflow/Chart.yaml
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/_helpers/validate-values.tpl
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

What this PR does:
* properly fixes the following issues (which were not properly fixed in PR https://github.com/airflow-helm/charts/pull/102):
- fixes #98
- fixes #101
* fixes some bad wording on the `airflow.config.AIRFLOW__CORE__DAGS_FOLDER` value validation.
* addresses an issue with our `PYTHONPATH` when using `*.extraPipPackages`, which was overriding anything that the user set with `airflow.extraEnv`:
- fixes #106
* fixes the `PYTHONPATH` not being set when using `airflow.kubernetesPodTemplate.extraPipPackages` with `pod_template.yaml`

release 8.0.2

---

charts/airflow/Chart.yaml
charts/airflow/files/pod_template.kubernetes-helm-yaml

fix wrong value for `envFrom` in kubernetes pod template

fix wrong value for `envFrom` in pod_template

---

charts/airflow/Chart.yaml
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

Signed-off-by: Yuan Gao <meseta@gmail.com>
- fixes #116 
Resolves the error "nil pointer evaluating interface {}.Name" when providing sshKnownHosts, which is caused by not passing the .Release object in the include context
As reported in #116, this issue also impacts using `dags.persistence.enabled: true`

add "Release"  to template context dict

---

charts/airflow/Chart.yaml
charts/airflow/templates/_helpers/validate-values.tpl
charts/airflow/templates/config/secret-config.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml

- fixes #112 
Extracts the liveness and readiness path for the web container from the configured airflow base path. 
Configures /health by default if no base path is configured

extract probe path from AIRFLOW__WEBSERVER__BASE_URL + ingress path validation 

---

charts/airflow/Chart.yaml
charts/airflow/README.md
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/validate-values.tpl
charts/airflow/templates/config/secret-config.yaml
charts/airflow/templates/flower/flower-ingress.yaml
charts/airflow/templates/jobs/job-create-connections.yaml
charts/airflow/templates/jobs/job-create-pools.yaml
charts/airflow/templates/jobs/job-create-users.yaml
charts/airflow/templates/jobs/job-create-variables.yaml
charts/airflow/templates/jobs/job-upgrade-db.yaml
charts/airflow/templates/jobs/secret-job-scripts.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/webserver/webserver-ingress.yaml
charts/airflow/values.yaml

A patch release with lots of fixes:
* fix dockerfile code blocks in README
* only include checksum/config-pod-template for kubernetes_like executors
* give more information in value validation errors 
* prevent embedded postgres/redis being enabled at same time as external 
* use _helper variable in pod_template envFrom 
* include airflow.podAnnotations in jobs
* partially closes https://github.com/airflow-helm/charts/pull/140
* add int64 to validation, so int variables set in bash work 
* closes https://github.com/airflow-helm/charts/issues/136
* add missing pod labels to upgrade-db job 
* fix validation for wildcard ingress paths 
* closes https://github.com/airflow-helm/charts/issues/144
* fix typo in connections example 
* closes https://github.com/airflow-helm/charts/pull/148
* fix …

release 8.0.7

---

charts/airflow/Chart.yaml
charts/airflow/README.md
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

This is a patch release which includes:
* dont include git-sync containers in webserver for airflow 2.0 
* closes https://github.com/airflow-helm/charts/issues/152
* ensure dags git repo is cloned before containers start
* closes https://github.com/airflow-helm/charts/issues/124
* introduce timeout for check-db init-container
* closes https://github.com/airflow-helm/charts/issues/153 
* only include git-sync init-container in pod_template if enabled
* closes https://github.com/airflow-helm/charts/issues/158
* add properties to externalDatabase docs

release 8.0.8

---

charts/airflow/Chart.yaml
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

This is a patch release which:
* make check-db timeout 60s
* closes https://github.com/airflow-helm/charts/issues/181
* move to `pip install --user` 
* closes https://github.com/airflow-helm/charts/issues/168
* closes https://github.com/airflow-helm/charts/issues/169

release 8.0.9

---

charts/airflow/Chart.yaml
charts/airflow/README.md
charts/airflow/UPGRADE.md
charts/airflow/examples/google-gke/custom-values.yaml

__Changes:__
* Fixes the lack of `UPGRADE.md` docs for the `8.1.0` version created by https://github.com/airflow-helm/charts/pull/175
* Removes references to `workers.celery.instances` (which was removed in `8.0.0`)

release 8.1.1

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml

Changes:
- Upgrades the versions of `helm`, `chart-testing`, `chart-releaser`
- Enables new `--skip-existing` feature of `chart-releaser` (https://github.com/helm/chart-releaser/pull/111)

upgrade github workflows

---

charts/airflow/templates/worker/worker-service.yaml

- Adds `{{ .Release.Name }}` to worker Service `spec.selector`, ensuring no conflicts if two airflow installs exist in the same namespace.

fix: add `release` to worker Service selector

---

charts/airflow/templates/_helpers/validate-values.tpl

- resolves https://github.com/airflow-helm/charts/issues/247
- Implements changes described in:
- https://github.com/airflow-helm/charts/issues/247

fix: only validate `ingress.{web, flower}.path` if `ingress.enabled=true`

---

charts/airflow/templates/scheduler/scheduler-deployment.yaml

- fixes https://github.com/airflow-helm/charts/issues/240
- Implements changes described in: https://github.com/airflow-helm/charts/issues/240

fix: multiple Schedulers could run if `legacyCommands=true` due to `rollingUpdate`

---

charts/airflow/templates/webserver/webserver-deployment.yaml

- resolves https://github.com/airflow-helm/charts/issues/251
- fixes https://github.com/airflow-helm/charts/issues/222#issuecomment-865765314
- removes the need for:
- https://github.com/airflow-helm/charts/issues/160
- Implements changes described in:
- https://github.com/airflow-helm/charts/issues/251

fix: deploy git-sync in webserver, regardless of `airflow.legacyCommands`

---

charts/airflow/templates/scheduler/scheduler-deployment.yaml

- fixes #340
- Fixed airflow scheduler `livenessProbe` so it exits with code `1` on error

fix: scheduler livenessProbe exit codes

---

charts/airflow/files/pod_template.kubernetes-helm-yaml

- fixes #349
- Make the KubernetesExecutor `pod_template.yaml` use the `airflow.image` _helper template, meaning these values are now respected:
-  `airflow.image.repository` (also being set by `AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY`) 
-  `airflow.image.tag` (also being set by `AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG`) 
- `airflow.image.pullPolicy`
- `airflow.image.uid`
- `airflow.image.gid`

fix: make pod_template use `airflow.image.*` values

---

charts/airflow/README.md
charts/airflow/templates/config/secret-config.yaml
charts/airflow/values.yaml

- resolves: https://github.com/airflow-helm/charts/issues/332
- fixes: https://github.com/airflow-helm/charts/issues/327
- fixes: https://github.com/airflow-helm/charts/issues/72
- https://github.com/airflow-helm/charts/issues/332
- Adds the following values:
- `airflow.webserverSecretKey` (default: `THIS IS UNSAFE!`)

feat: add `airflow.webserverSecretKey` value

---

charts/airflow/README.md
charts/airflow/templates/_helpers/pods.tpl

- resolves https://github.com/airflow-helm/charts/issues/324
- fixes https://github.com/airflow-helm/charts/issues/115
- fixes https://github.com/airflow-helm/charts/issues/322
- Includes `airflow.config` and `airflow.extraEnv` in the pip-install init-container, as described in:
- https://github.com/airflow-helm/charts/issues/324
- Adds docs for how to set `--index-url` with `extraPipPackages`

feat: include `airflow.{config,extraEnv}` in pip-install container

---

charts/airflow/templates/sync/_helpers/global_code.tpl
charts/airflow/templates/sync/_helpers/snyc_connections.tpl
charts/airflow/templates/sync/_helpers/snyc_pools.tpl
charts/airflow/templates/sync/_helpers/snyc_variables.tpl
charts/airflow/templates/sync/_helpers/sync_users.tpl
charts/airflow/templates/sync/sync-connections-deployment.yaml
charts/airflow/templates/sync/sync-connections-job.yaml
charts/airflow/templates/sync/sync-connections-secret.yaml
charts/airflow/templates/sync/sync-pools-deployment.yaml
charts/airflow/templates/sync/sync-pools-job.yaml
charts/airflow/templates/sync/sync-pools-secret.yaml
charts/airflow/templates/sync/sync-users-deployment.yaml
charts/airflow/templates/sync/sync-users-job.yaml
charts/airflow/templates/sync/sync-users-secret.yaml
charts/airflow/templates/sync/sync-variables-deployment.yaml
charts/airflow/templates/sync/sync-variables-job.yaml
charts/airflow/templates/sync/sync-variables-secret.yaml

- resolves https://github.com/airflow-helm/charts/issues/364
- Replaces "snyc" -> "sync" in `sync/_helpers` templates

fix: typos in sync/_helpers templates

---

charts/airflow/README.md
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/values.yaml

- resolves https://github.com/airflow-helm/charts/issues/382
- Removes the `flower.oauthDomains` value, for the reasons described in:
- https://github.com/airflow-helm/charts/issues/382

refactor: remove broken `flower.oauthDomains` value

---

charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/flower/flower-deployment.yaml

- resolves https://github.com/airflow-helm/charts/issues/384
- Implements the change described in:
- https://github.com/airflow-helm/charts/issues/384

fix: always include `airflow.env` last

---

charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/jobs/job-upgrade-db.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/sync/sync-connections-deployment.yaml
charts/airflow/templates/sync/sync-connections-job.yaml
charts/airflow/templates/sync/sync-pools-deployment.yaml
charts/airflow/templates/sync/sync-pools-job.yaml
charts/airflow/templates/sync/sync-users-deployment.yaml
charts/airflow/templates/sync/sync-users-job.yaml
charts/airflow/templates/sync/sync-variables-deployment.yaml
charts/airflow/templates/sync/sync-variables-job.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

- resolves https://github.com/airflow-helm/charts/issues/336
- Start using the default `/entrypoint` for Airflow 2.0+ (when `airflow.legacyCommands=false`).
- First step towards out-of-the-box OpenShift support (`/entrypoint` handles most OpenShift issues as of airflow `2.1.2`)

feat: use `/entrypoint` when `airflow.legacyCommands=false`

---

charts/airflow/values.yaml

- resolves https://github.com/airflow-helm/charts/issues/337
- Sets the default `airflow.image.gid` to `0`.

refactor: set default `airflow.image.gid=0`

---

charts/airflow/README.md
charts/airflow/templates/_helpers/common.tpl
charts/airflow/templates/_helpers/validate-values.tpl
charts/airflow/templates/config/secret-config.yaml
charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl
charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml
charts/airflow/templates/pgbouncer/pgbouncer-pdb.yaml
charts/airflow/templates/pgbouncer/pgbouncer-secret-certs.yaml
charts/airflow/templates/pgbouncer/pgbouncer-secret.yaml
charts/airflow/templates/pgbouncer/pgbouncer-service.yaml
charts/airflow/values.yaml

- resolves #235
- fixes #227
- Implements [PgBouncer](https://www.pgbouncer.org/) to pool connections and reduce the possibility of "too many connections" errors:
- `pgbouncer.enabled` (default: `true`)
- `pgbouncer.image`:
- `pgbouncer.image.repository` (default: `ghcr.io/airflow-helm/pgbouncer`)
- `pgbouncer.image.tag` (default =`1.15.0-patch.0`)
- `pgbouncer.image.pullPolicy`(default: `IfNotPresent`)
- `pgbouncer.image.uid` (default: `1001`)
- `pgbouncer.image.gid` (default: `1001`)
- `pgbouncer.resources`
- `pgbouncer.nodeSelector`
- `pgbouncer.affinity`
- `pgbouncer.tolerations`
- `pgbouncer.securityContext`
- `pgbouncer.labels`
- `pgbouncer.podLabels`
- `pgbouncer.annotations`
- `pgbouncer.podAnnotations`
- …

feat: implement pgbouncer support

---

charts/airflow/templates/db-migrations/db-migrations-deployment.yaml
charts/airflow/templates/db-migrations/db-migrations-job.yaml
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/sync/sync-connections-deployment.yaml
charts/airflow/templates/sync/sync-connections-job.yaml
charts/airflow/templates/sync/sync-pools-deployment.yaml
charts/airflow/templates/sync/sync-pools-job.yaml
charts/airflow/templates/sync/sync-users-deployment.yaml
charts/airflow/templates/sync/sync-users-job.yaml
charts/airflow/templates/sync/sync-variables-deployment.yaml
charts/airflow/templates/sync/sync-variables-job.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

- resolves https://github.com/airflow-helm/charts/issues/375
- resolves https://github.com/airflow-helm/charts/issues/276
- Allow "airflow plugins" and "python packages" to be stored in the DAGs git repo:
- Includes the `git-sync` init-container and sidecar container in all Deployments
- Orders the init-containers so that `git-sync` comes before `check_db` and `wait_for_db_migrations`

fix: include git-sync in all Deployments

---

charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl

- resolves https://github.com/airflow-helm/charts/issues/396
- Fixes PgBouncer with `postgresql.postgresqlDatabase` or `externalDatabase.database` set to a value other than `airflow`
- https://github.com/airflow-helm/charts/issues/396

fix: pgbouncer config for non-default database name

---

charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl
charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml
charts/airflow/templates/pgbouncer/pgbouncer-secret-certs.yaml
charts/airflow/values.yaml

- resolve https://github.com/airflow-helm/charts/issues/402
- https://github.com/airflow-helm/charts/issues/402
- Prevents errors like `routines:ssl3_read_bytes:tlsv1 alert unknown ca` in PgBouncer

fix: only gen self-signed certs for pgbouncer client configs

---

charts/airflow/templates/flower/flower-deployment.yaml

- resolves https://github.com/airflow-helm/charts/issues/403
- Makes the flower Deployment affected by `airflow.{defaultNodeSelector,defaultAffinity,defaultTolerations}`

fix: make flower affected by default nodeSelector, affinity, tolerations

---

charts/airflow/values.yaml

- fixes https://github.com/airflow-helm/charts/issues/484
This PR changes the default values for `timeoutSeconds` as follows:
- `scheduler.livenessProbe.timeoutSeconds` (old: `10`, new: `60`)
- `pgbouncer.livenessProbe.timeoutSeconds` (old: `15`, new: `60`)

fix: increase default `timeoutSeconds` for probes

---

charts/airflow/templates/_helpers/pods.tpl

- `GIT_SYNC_MAX_SYNC_FAILURES` is the [correct environment variable name](https://github.com/kubernetes/git-sync#parameters)

fix: typo in `GIT_SYNC_MAX_SYNC_FAILURES` envvar

---

charts/airflow/values.yaml

- related to https://github.com/airflow-helm/charts/issues/397
- Updates the default PGBouncer image to `ghcr.io/airflow-helm/pgbouncer:1.17.0-patch.0`

feat: update pgbouncer image tag `1.17.0-patch.0`

---

charts/airflow/templates/worker/worker-statefulset.yaml

- resolves https://github.com/airflow-helm/charts/issues/428
- Sets `DUMB_INIT_SETSID=0` on the celery workers:
- makes dumb-init only send SIGTERM/SIGKILL/etc to direct child process (needed for celery workers to warm shutdown successfully)
- Makes the Airflow Celery Worker containers use the same `command` (entrypoint) as the rest of the Airflow Deployments
- ___NOTE:__ our previous reasonsing for including `bash -c` in the `command` was invalid, as `lifecycle.preStop` does not run with the containers defined `command`, but by directly `exec`'ing into the container)_

fix: set `DUMB_INIT_SETSID=0` for celery workers (warm shutdown) 

---

charts/airflow/README.md
charts/airflow/templates/sync/_helpers/sync_users.tpl
charts/airflow/values.yaml

- resolves #538 
- Alows `airflow.users[].roles` to be either a list of `flask_appbuilder` role-names, or a single role-name string.

feat: allow `airflow.users[].roles` to specify a list of roles

---

charts/airflow/README.md
charts/airflow/templates/NOTES.txt
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/config/secret-config-envs.yaml
charts/airflow/values.yaml

- resolves https://github.com/airflow-helm/charts/issues/511
- Added values to set externalDatabase/externalRedis passwords directly with plain-text values:
- `externalDatabase.password`
- `externalRedis.password`
- Added values to set externalDatabase username from a secret:
- `externalDatabase.userSecret`
- `externalDatabase.userSecretKey` (default: `postgresql-user`)
- Added warning to NOTES.txt if user sets externalDatabase/externalRedis using the plain-text values.

feat: database passwords with values + username from secret

---

charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml

N/A
- Fixes the `pgbouncer.livenessProbe.enabled` value not being respected

fix: `pgbouncer.livenessProbe.enabled` not being respected

---

charts/airflow/README.md
charts/airflow/templates/NOTES.txt
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/values.yaml

- related to #512 
-  _(NOTE: this PR probably does not fix that issue fully)_
- supersedes https://github.com/airflow-helm/charts/pull/541
- Adds an optional "task creation check" to the scheduler liveness probe:
- `scheduler.livenessProbe.taskCreationCheck.enabled` (default: `false`)
- `scheduler.livenessProbe.taskCreationCheck.thresholdSeconds` (default: `300`)
- Adds a new FAQ "How to configure the scheduler liveness probe?" with sub-sections:
- `Scheduler "Heartbeat Check"`
- `Scheduler "Task Creation Check"`
- Runs the scheduler livenessProbe with `/entrypoint`:
- ___NOTE:__ this ensures any fixes inside `/entrypoint` are applied in our livenessProbe_
- ___NOTE:__ this improves support for running as root (airflow python packages will not be visible otherwise)_
- Makes the scheduler …

feat: add "task creation check" to scheduler liveness probe

---

charts/airflow/README.md
charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml
charts/airflow/values.yaml

- fixes https://github.com/airflow-helm/charts/issues/525
- resolves https://github.com/airflow-helm/charts/issues/526
- Replaces the PgBouncer "readinessProbe" with a "startupProbe" to prevent intermittent socket failures causing the "livenessProbe" to fail:
- ___WARNING:__ "startupProbe" was made [beta in Kubernetes 1.18](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#features-graduated-to-beta), so older versions of Kubernetes may not respect the "startupProbe"_
- ___NOTE:__ see https://github.com/airflow-helm/charts/issues/526 for context_
- Added the following values:
- `pgbouncer.startupProbe.enabled` (default: `true`)
- `pgbouncer.startupProbe.initialDelaySeconds` (default: `5`)
- `pgbouncer.startupProbe.periodSeconds` (default: `10`)
- …

fix: replace pgbouncer readinessProbe with startupProbe

---

charts/airflow/README.md
charts/airflow/values.yaml

- N/A
- Increases the default `pgbouncer.maxClientConnections` from `100` to `1000`
- ___NOTE:__ `1000` is well beyond what should be required in most deployments, so this should prevent users from running into a confusing situation where the connection limit is exceeded, and random things start failing (with the only error logs being in the PGBouncer deployment)_

feat: set default `pgbouncer.maxClientConnections` to 1000

---

charts/airflow/values.yaml

- fixes https://github.com/airflow-helm/charts/issues/414
- related to https://github.com/airflow-helm/charts/issues/518
- Updates the default `dags.gitSync.image.tag` from `v3.2.2` to `v3.5.0`

fix: update default `dags.gitSync.image.tag` to v3.5.0

---

charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/values.yaml

Sometimes it is necessary to set Pod labels on the KubernetesExecutor pod_template.
For example, when running a cluster with an older version of Istio, [there is a bug which can result in Istio applying a label that is longer than the 63 character limit](https://github.com/istio/istio/issues/25157), users work around this issue by applying an `app.kubernetes.io/name` or `app` label to the Pod.
The PR allows you to define the labels in the `kubernetesPodTemplate`, something that was previously only possible by adding in the whole of the pod template via the `airflow.kubernetesPodTemplate.stringOverride` variable.
- Adds the `airflow.kubernetesPodTemplate.podLabels` value to set Pod labels on the KubernetesExecutor pod_template.

feat: add `airflow.kubernetesPodTemplate.podLabels` value

---

charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl

- fixes #532
The double-setting of `CONNECTION_CHECK_MAX_COUNT` was preventing the airflow scheduler from adopting pods due to k8s thinking the env var value was changing when the pod was being patched:
```
[2022-02-24 22:24:48,385] {kubernetes_executor.py:665} INFO - attempting to adopt pod podname.69b7727977014e948bc0b31cb2946803
[2022-02-24 22:24:48,399] {kubernetes_executor.py:683} INFO - Failed to adopt pod podname.69b7727977014e948bc0b31cb2946803. Reason: (422)
Reason: Unprocessable Entity
... is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations`
```
The change in question that is preventing the patch request:
```
Name: …
```

fix: only set `CONNECTION_CHECK_MAX_COUNT` once

---

charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/values.yaml

I was looking for a nice way to deal with secrets in airflow. As we already use Hashicorp Vault everywhere and are very happy with it I was looking for a good way to make airflow work with it.
There is a [Vault secret backend](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/secrets-backends/hashicorp-vault.html#hashicorp-vault-secrets) in Airflow but it's very basic. The feature I mostly want to use is to get dynamic credentials for accessing databases, with credentials that will live the time of the pod (dag). For the rest, airflow vars and connections are fine.
I tried to use [Vault CSI](https://github.com/hashicorp/vault-csi-provider) but it's still early stage and also does not fulfill what I want to do. In the end, I just did what I do in other projects: …

feat: add `airflow.kubernetesPodTemplate.shareProcessNamespace` value

---

charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/values.yaml

N/A
- Adds the `airflow.kubernetesPodTemplate.extraInitContainers` value to specify extra KubernetesExecutor init-containers

feat: add `airflow.kubernetesPodTemplate.extraInitContainers`

---

charts/airflow/README.md
charts/airflow/templates/config/secret-config-envs.yaml
charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl
charts/airflow/values.yaml

- fixes https://github.com/airflow-helm/charts/issues/476
- Adds a `airflow.clusterDomain` value (default: `cluster.local`) to allow setting the Kubelet `clusterDomain` to non-standard values.

feat: add `airflow.clusterDomain` value

---

charts/airflow/README.md
charts/airflow/templates/config/secret-config-envs.yaml
charts/airflow/values.yaml

- fixes #506 
- Only set `AIRFLOW__CORE__FERNET_KEY` and `AIRFLOW__WEBSERVER__SECRET_KEY` when the values of `airflow.fernetKey` and `airflow.webserverSecretKey` are non-empty. 
- Allows the use of the `_CMD` and `_SECRET` variables, which are currently overshadowed by their non-suffixed versions.

fix: `airflow.{fernetKey,webserverSecretKey}` overshadow `_CMD` configs

---

charts/airflow/templates/flower/flower-ingress.yaml
charts/airflow/templates/webserver/webserver-ingress.yaml

- fixes https://github.com/airflow-helm/charts/issues/477
When we migrated to the `networking.k8s.io/v1` version of Ingress, we incorrectly assumed that `ingress.web.precedingPaths[].servicePort` would always be a number, when previously it could be a port-name also.
This PR, ensure that we place the `servicePort` into the correct Ingress field, depending on if it is a string or a number.

fix: allow ingress `servicePort` to be string or number

---

charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl

Currently, the `db-migrations` Deployment will hang forever after printing `WARNING - there are unapplied db migrations, triggering apply... ` when attempting to upgrade airflow from `2.2.X` to something newer.
When this happens, the only solution is to restart the PgBouncer Pod.
As of Airflow 2.2.0, the [`upgradedb()`](https://github.com/apache/airflow/blob/2.2.0/airflow/utils/db.py#L822) command now [creates a `PG_ADVISORY_LOCK`](https://github.com/apache/airflow/blob/2.2.0/airflow/utils/session.py#L82).
We run PgBouncer in [`pool_mode = transaction`](https://github.com/airflow-helm/charts/blob/df99a33e3278de9f6935e747e8317794966ed979/charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl#L13), in this mode, locks will never be released, because the "lock" and "unlock" statements are …

fix: PG_ADVISORY_LOCK are not released in pgbouncer

---

charts/airflow/README.md
charts/airflow/templates/extra-manifests.yaml
charts/airflow/values.yaml

- resolves https://github.com/airflow-helm/charts/issues/522
- Allows for elements of `extraManifests` to be strings (not objects), which enables full support for Helm templating.
- Updates the docstring/readme with examples of string-based `extraManifests` that use complex Helm templating.
- Existing users who specified `extraManifests` as a list of objects (not strings) should not be impacted by this change.
- We intend for new users to specify `extraManifests` as a list of strings, so they can make full use of Helm templating.

feat: fully support helm templating in `extraManifests`

---

charts/airflow/README.md
charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl
charts/airflow/values.yaml

- fixes https://github.com/airflow-helm/charts/issues/412
- resolves https://github.com/airflow-helm/charts/issues/419
- Adds the `pgbouncer.authType` value (default: `md5`) to set the `auth_type` config of PgBouncer.
- ___NOTE:__ this is important for "Azure PostgreSQL" as the default  `md5` will not work, but `scram-sha-256` will_

feat: add `pgbouncer.authType` value

---

charts/airflow/README.md
charts/airflow/examples/google-gke/custom-values.yaml
charts/airflow/examples/minikube/custom-values.yaml
charts/airflow/templates/_helpers/common.tpl
charts/airflow/templates/config/secret-config-envs.yaml
charts/airflow/templates/triggerer/triggerer-deployment.yaml
charts/airflow/templates/triggerer/triggerer-pdb.yaml
charts/airflow/values.yaml

- resolves https://github.com/airflow-helm/charts/issues/424
- supersedes & closes https://github.com/airflow-helm/charts/pull/521
- _(some further changes were needed, and I did not have write access to that repo)_
- Adds a new Deployment for the [`airflow triggerer`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#triggerer) so we fully support Airflow's [Deferrable Tasks](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html) feature.
- ___WARNING:__ `airflow triggerer` was added in airflow `2.2.0`, so will crash-loop if enabled in previous versions_
- ___NOTE:__ The triggerer deployment is automatically (and silently) disabled in the following situations:_
- _if `airflow.legacyCommands` is `true`_
- _if …

feat: add `airflow triggerer` Deployment

---

charts/airflow/templates/config/secret-config-envs.yaml

- N/A
- Cast user-provided values with `toString` before passing to `b64enc`, preventing helm syntax errors if int-type values are passed when strings are expected.
- ___NOTE:__ this is most likely to affect user/password values, as number-only values are possible:_
- `externalDatabase.user`
- `externalDatabase.password`
- `externalRedis.password`

fix: cast user values with toString before b64enc

---

README.md
charts/airflow/.helmignore
charts/airflow/CHANGELOG.md
charts/airflow/Chart.yaml
charts/airflow/README.md
charts/airflow/docs/faq/configuration/airflow-version.md
charts/airflow/values.yaml

- N/A
- Releases version `8.6.0` of the chart
- Updates the default `airflow.image.tag` to `2.2.5-python3.8`

chore: release `8.6.0`

---

charts/airflow/README.md
charts/airflow/docs/faq/configuration/extra-python-packages.md
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/values.yaml

- related to https://github.com/airflow-helm/charts/discussions/605
- probably related to https://github.com/airflow-helm/charts/issues/597
- Prevents `extraPipPackages` from changing the version of any pip package listed in `airflow.protectedPipPackages`.
- This feature works by adding a `pip --constraint` file that we generate from the filtered output of `pip freeze` when installing `extraPipPackages`.
- The initial default for `airflow.protectedPipPackages` is `["apache-airflow"]`, which will hopefully stop people from accidentally running a different airflow version than specified in their `airflow.image.tag`.
- ___WARNING:__ if users currently have `extraPipPackages` configs that are causing their `apache-airflow` version to be changed, their pods will now crash loop. To resolve …

feat: add `airflow.protectedPipPackages`

---

charts/airflow/templates/config/secret-config-envs.yaml

- fixes https://github.com/airflow-helm/charts/issues/558
- Changes the PgBouncer liveness probe to use `172.0.0.1` rather than `airflow-pgbouncer.airflow.svc.cluster.local`
- ___NOTE:__ this is necessary because minikube does not allow Pods to access their own `cluster.local` services https://github.com/kubernetes/minikube/issues/1568_

fix: pgbouncer liveness probe in minikube

---

charts/airflow/templates/config/secret-config-envs.yaml

- fixes https://github.com/airflow-helm/charts/issues/604
- Sets the new `AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT` which replaced `AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT` in airflow 2.2.0 (NOTE: we now set both to keep backward compatibility)

fix: set AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT

---

charts/airflow/files/webserver_config.py

- N/A
- Updates the default `webserver_config.py` template to only set `SQLALCHEMY_DATABASE_URI` when `airflow.legacyCommands` is `true` (as it only needs to be set for airflow 1.10).

fix: only set SQLALCHEMY_DATABASE_URI in airflow 1.10

---

charts/airflow/templates/_helpers/validate-values.tpl

- fixes #588
- Lowers the maximum length of the helm release name to `40` (down from `43`)
- This is needed because the embedded PostgreSQL and Redis charts will create a StatefulSets having a name that is `54` characters long when the helm release is `41` characters long, making it unable to create Pods (https://github.com/kubernetes/kubernetes/issues/64023)
- As an escape hatch for people with existing deployments that have release names between `41` and `43` characters, a hidden value called `allowLongReleaseName` has been added, which reverts to the previous limit of `43`.

fix: require release-name to have <= 40 characters

---

charts/airflow/templates/_helpers/validate-values.tpl
charts/airflow/templates/config/secret-config-envs.yaml
charts/airflow/templates/sync/_helpers/sync_users.tpl

- partially resolves https://github.com/airflow-helm/charts/issues/572
- fixes https://github.com/airflow-helm/charts/issues/607
- Fixes breaking changes introduced in Airflow 2.3.0 (but does not update the default airflow image tag)
- Sets the `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD` variable (as `AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD` was not correctly depreciated in Airflow 2.3.0)
- Fixes `sync-users` script by updating imports for `User` and `Role` models, first trying `airflow.www.fab_security.sqla.models` (Airflow 2.3+) and if that fails, `flask_appbuilder.security.sqla.models` (Airflow <2.3)

fix: some breaking changes from airflow 2.3.0

---

charts/airflow/templates/db-migrations/_helpers/code.tpl

- related to https://github.com/airflow-helm/charts/issues/572
- Fixes an issue due to a breaking change in Airflow 2.3.0 where the db-migration logic always thinks there are pending migrations if `timeout=0`.
- [Old loop for Airflow 2.2.5](https://github.com/apache/airflow/blob/2.2.5/airflow/utils/db.py#L638)
- [New loop for Airflow 2.3.0](https://github.com/apache/airflow/blob/2.3.0/airflow/utils/db.py#L696)
- This change should be backward-compatible with pre-Airflow 2.3.0 as well, it'll just loop one more time.

fix: wait-for-db-migrations in airflow 2.3.0

---

charts/airflow/templates/_helpers/pods.tpl

- fixes https://github.com/airflow-helm/charts/issues/598
- Uses `rsync --delete` for the extraPipPackages init-container, so if the init-container is rerun, any extra existing files on the `emptyDir` volume are deleted.
- Also sets the `rsync --stats` arg to highlight to users how much data is being copied (and how fast).

fix: use rsync for extraPipPackages

---

charts/airflow/.helmignore

- N/A
- Updates the `.helmignore` file to exclude chart documentation, reducing the size of the helm package.

chore: update .helmignore to exclude docs

---

charts/airflow/docs/faq/monitoring/log-persistence.md
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/NOTES.txt
charts/airflow/templates/_helpers/common.tpl
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/_helpers/validate-values.tpl
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/triggerer/triggerer-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml

- fixes https://github.com/airflow-helm/charts/issues/571
- Fixes support for `logs.path` being under a custom `airflow.extraVolumeMounts` by detecting when this happens and disabling the `emptyDir` Volume mounted at `logs.path` (originally broken by https://github.com/airflow-helm/charts/pull/554)
- Prevent using `airflow.extraVolumeMounts` for logs at the same time as log-cleanup. This is for the same reasons as with `logs.persistence`, namely that multiple pods would fight over deleting, but mostly because auto-deleting logs is usually not what the user wants if they enable persistence.
- Added `"Option 3 - Pod Volumes"` to the `"How to persist airflow logs?"` FAQ page

feat: allow using extraVolumeMounts for log storage

---

charts/airflow/docs/faq/monitoring/scheduler-liveness-probe.md
charts/airflow/examples/google-gke/custom-values.yaml
charts/airflow/examples/minikube/custom-values.yaml
charts/airflow/sample-values-CeleryExecutor.yaml
charts/airflow/sample-values-CeleryKubernetesExecutor.yaml
charts/airflow/sample-values-KubernetesExecutor.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/values.yaml

- N/A
- Currently, the scheduler can be killed by the "task creation check" before it actually had time to schedule a task, this PR adds `scheduler.livenessProbe.taskCreationCheck.schedulerAgeBeforeCheck` (default: `180`), which defines the minimum scheduler age (seconds from the start_date of the SchedulerJob) before we start checking for task creation.

feat: minimum scheduler age before task-creation-check

---

charts/airflow/docs/faq/configuration/airflow-version.md
charts/airflow/docs/guides/quickstart.md

- broken links in documentation
This PR makes the following changes...

docs: fix relative link anchors to readme

---

charts/airflow/docs/faq/configuration/airflow-configs.md
charts/airflow/templates/config/secret-webserver-config.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/values.yaml

Allow users to disable the chart-managed `webserver_config.py`:
- this can be used when the container image has a `webserver_config.py` file baked in, or when the user wants to mount the file with a custom volume mount
- new value `web.webserverConfig.enabled` (default: `true`)

feat: allow disabling chart-managed `webserver_config.py`

---

charts/airflow/templates/_helpers/pods.tpl
charts/airflow/values.yaml

Signed-off-by: Burak Karakan <burak.karakan@gmail.com>
- N/A
This PR introduces a new value `dags.gitSync.submodules` (default: `recursive`) to control the submodule strategy for git-sync pods.
In my use case, the repo that is being cloned has a lot of submodules, but I would rather not init the submodules because it takes 20+ seconds, therefore I want to be able to disable the submodules to significantly speed up my tasks.

feat: add `dags.gitSync.submodules` value

---

charts/airflow/templates/config/secret-config-envs.yaml

- fixes #677
This PR additionally sets the `kubernetes_executor` equivalent of any `kubernetes` airflow configs we set, to suppress deprecation warnings in pod logs.

fix: also set `kubernetes_executor` airflow configs

---

charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/triggerer/triggerer-deployment.yaml

- fixes https://github.com/airflow-helm/charts/issues/737
- supersedes https://github.com/airflow-helm/charts/pull/738
- supersedes https://github.com/airflow-helm/charts/pull/742
This PR fixes support for airflow 2.6.0 in the chart. Due to PR https://github.com/apache/airflow/pull/30302, airflow's Job objects `SchedulerJob` and `TriggererJob` were changed so they are now wrapped in an `XXXXJobRunner` object, which broke our scheduler and triggerer liveness probes.
There is a related upstream airflow issue https://github.com/apache/airflow/issues/31200 introduced by Airflow 2.6.0 (which can't really be fixed by this chart), the details of that issue are explained in https://github.com/apache/airflow/issues/31200#issuecomment-1546765025, so you should strongly consider waiting for at least …

fix: liveness probes in airflow 2.6.0

---

charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml

- fixes #765 
Some systems which are strict about schema validation will fail if a projected volume does not specify `sources`.
This PR ensures we only include the `pgbouncer-certs` volume when it has at least one source.

fix: invalid pgbouncer-certs volume spec when empty

---

charts/airflow/docs/faq/dags/airflow-pools.md
charts/airflow/templates/sync/_helpers/sync_pools.tpl
charts/airflow/values.yaml

Airflow 2.7.0 added the `include_deferred` column to the `Pool` object (see https://github.com/apache/airflow/pull/32709), since this column is non-nullable, we must set it.
The same as upstream, our default state for `include_deferred` is `False`, if not specified.
Add support for `include_deferred` to `sync_pools.tpl` so it will create and update pools successfully.

feat: support `include_deferred` in pool sync for airflow 2.7.0

---

charts/airflow/templates/sync/_helpers/sync_users.tpl

- fixes https://github.com/apache/airflow/issues/33635 (which was created in the airflow repo)
- fixes https://github.com/airflow-helm/charts/discussions/771
Updates this import path to be Airflow 2.7.0-friendly

fix: sync-users for airflow 2.7.0

---

charts/airflow/README.md
charts/airflow/templates/worker/worker-statefulset.yaml
charts/airflow/values.yaml

- fixes #600 
Currently celery workers can enter a 'zombie' state where they become disconnected from celery and will no longer pick up new jobs. 
This PR adds a iveness probe (enabled by default) to detect such pods so they can be killed by k8s and recreated.

feat: add liveness probe for celery workers

---

charts/airflow/docs/faq/security/ldap-oauth.md

- related to https://github.com/airflow-helm/charts/discussions/605#discussioncomment-2981762
Updates the docs for Okta OAUTH integration to use the format required in Airflow 2.3.3+:
- https://github.com/dpgaspar/Flask-AppBuilder/issues/1861
- https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-2-3-3-2022-07-09
Specifically, you now need to either set `server_metadata_url` or `jwks_uri` for OIDC to work.

docs: fix okta oauth example for airflow 2.3.3+

---

charts/airflow/README.md
charts/airflow/docs/faq/kubernetes/affinity-node-selectors-tolerations.md
charts/airflow/files/pod_template.kubernetes-helm-yaml
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/db-migrations/db-migrations-deployment.yaml
charts/airflow/templates/db-migrations/db-migrations-job.yaml
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/sync/sync-connections-deployment.yaml
charts/airflow/templates/sync/sync-connections-job.yaml
charts/airflow/templates/sync/sync-pools-deployment.yaml
charts/airflow/templates/sync/sync-pools-job.yaml
charts/airflow/templates/sync/sync-users-deployment.yaml
charts/airflow/templates/sync/sync-users-job.yaml
charts/airflow/templates/sync/sync-variables-deployment.yaml
charts/airflow/templates/sync/sync-variables-job.yaml
charts/airflow/templates/triggerer/triggerer-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml
charts/airflow/values.yaml

- Resolves https://github.com/airflow-helm/charts/issues/581
- `airflow.defaultTopologySpreadConstraints` (default: `[]`)
- `airflow.kubernetesPodTemplate.topologySpreadConstraints` (default: `[]`)
- `airflow.dbMigrations.topologySpreadConstraints` (default: `[]`)
- `airflow.sync.topologySpreadConstraints` (default: `[]`)
- `scheduler.topologySpreadConstraints` (default: `[]`)
- `web.topologySpreadConstraints` (default: `[]`)
- `workers.topologySpreadConstraints` (default: `[]`)
- `triggerer.topologySpreadConstraints` (default: `[]`)
- `flower.topologySpreadConstraints` (default: `[]`)
- `pgbouncer.topologySpreadConstraints` (default: `[]`)

feat: add `topologySpreadConstraints` values

---

charts/airflow/README.md
charts/airflow/templates/rbac/airflow-role.yaml
charts/airflow/values.yaml

- N/A
Currently, if a user wants to allow airflow Pods to read Secret resources, they must set `rbac.enabled` to false and provision their own Role/RoleBinding.
- `rbac.secrets` (default: `false`)
- If `true`, the RBAC Role used by airflow Pods will be allowed to GET/LIST/WATCH on Secret resources

feat: add optional `rbac.secrets` value to give GET/LIST/WATCH on Secrets

---

charts/airflow/README.md
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml
charts/airflow/values.yaml

Signed-off-by: Philipp Hitzler <philipp.hitzler@idealo.de>
- fixes #578 (except for Postgres and Redis)
This PR adds the following values: 
- `airflow.defaultContainerSecurityContext` (default: `{}`)
- Sets the Container SecurityContext of all airflow containers (including PGBouncer)
- Does not set `runAsUser` and `runAsGroup` (those are set per-image with the `*.image.uid` and `*.image.gid` values)
- Will NOT set Container SecurityContext of embedded Postgres or Redis due to still using the old charts:
- #303 
- #304
@thesuperzapper all code is taken from your https://github.com/airflow-helm/charts/issues/578#issuecomment-1147170097

feat: add `airflow.defaultContainerSecurityContext` value

---

charts/airflow/README.md
charts/airflow/templates/pgbouncer/_helpers/pgbouncer.tpl
charts/airflow/values.yaml

- fixes #819 
- `pgbouncer.statsUsers` (default: `""`)
- Sets the `stats_users` PgBouncer config in the `pgbouncer.ini` file.

feat: add `stats_users` configuration option for pgbouncer

---

charts/airflow/templates/_helpers/common.tpl
charts/airflow/templates/flower/flower-service.yaml
charts/airflow/templates/pgbouncer/pgbouncer-service.yaml
charts/airflow/templates/webserver/webserver-service.yaml
charts/airflow/templates/worker/worker-service.yaml

- fixes https://github.com/airflow-helm/charts/issues/545
- fixes https://github.com/airflow-helm/charts/issues/499
- closes https://github.com/airflow-helm/charts/pull/493
- related https://github.com/airflow-helm/charts/issues/510
- related https://github.com/airflow-helm/charts/discussions/566
This PR sets the `appProtocol` field on all our Service ports. 
This will help users who have Istio installed on their cluster, as it will prevent [automatic protocol detection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection) (which may fail in some cases).

fix: set `appProtocol` on Service ports (for Istio)

---

charts/airflow/README.md
charts/airflow/templates/_helpers/pods.tpl
charts/airflow/values.yaml

- fixes https://github.com/airflow-helm/charts/issues/242
- fixes https://github.com/airflow-helm/charts/issues/808
- closes https://github.com/airflow-helm/charts/pull/684
- closes https://github.com/airflow-helm/charts/pull/801
This PR allows you to set the resource request/limits for the few remaining init-containers for which there was not already values.
- `airflow.initContainers.checkDb.resources` (default: `{}`)
- Sets resources requests/limits for `check-db` init-containers
- `airflow.initContainers.waitForDbMigrations.resources` (default: `{}`)
- Sets resources requests/limits for `wait-for-db-migrations` init-containers
- `airflow.initContainers.installPipPackages.resources` (default: `{}`)
- Sets resources requests/limits for …

feat: add values to set init-container resources

---

charts/airflow/README.md
charts/airflow/templates/flower/flower-deployment.yaml
charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/triggerer/triggerer-deployment.yaml
charts/airflow/templates/webserver/webserver-deployment.yaml
charts/airflow/templates/worker/worker-statefulset.yaml
charts/airflow/values.yaml

- closes https://github.com/airflow-helm/charts/pull/651
- closes https://github.com/airflow-helm/charts/pull/788
This PR adds values for `extraContainers` and `extraInitContainers` for all Deployments.
- `airflow.extraInitContainers` (default: `[]`)
- `scheduler.extraContainers` (default: `[]`)
- `web.extraContainers` (default: `[]`)
- `web.extraInitContainers` (default: `[]`)
- `workers.extraContainers` (default: `[]`)
- `workers.extraInitContainers` (default: `[]`)
- `triggerer.extraContainers` (default: `[]`)
- `triggerer.extraInitContainers` (default: `[]`)
- `flower.extraContainers` (default: `[]`)
- `flower.extraInitContainers` (default: `[]`)

feat: add `extraContainers` and `extraInitContainers` values for all components

---

charts/airflow/templates/scheduler/scheduler-deployment.yaml
charts/airflow/templates/triggerer/triggerer-deployment.yaml

- fixes #829
Previously, we were not correctly filtering on the `job_type` field in the liveness probes for the Scheduler and Triggerer in Airflow versions older than 2.6.0.
This caused each probe to scan the entire `job` table, which is obviously very slow!

fix: scheduler and triggerer probe performance for airflow <2.6.0

---

charts/airflow/templates/sync/_helpers/sync_users.tpl

- fixes https://github.com/airflow-helm/charts/issues/847
- closes https://github.com/airflow-helm/charts/pull/848
I give up, I have no idea why they keep moving the FAB `User` and `Role` models around, but we don't really need to import them anyway (they were only for type hints).

fix: don't import User and Role FAB models, fixes airflow 2.9.0+

---

charts/airflow/templates/_helpers/pods.tpl

- fixes https://github.com/airflow-helm/charts/issues/847#issuecomment-2066951783
This PR fixes the `extraPipPackages` values in Airflow 2.9.0+
This was needed because upstream airflow changed to using Virtual Environments for Python in their Docker images (https://github.com/apache/airflow/pull/37796), and those don't support the `--user` flag with `pip install`.

fix: `extraPipPackages` values for airflow 2.9.0+
