airflow-helm/charts

charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/UPGRADE.md, charts/airflow/templates/config/configmap-scripts.yaml, charts/airflow/templates/scheduler/scheduler-deployment.yaml, charts/airflow/values.yaml
- fixes #33
- replaces #2
See `UPGRADE.MD`
* Start using `airflow upgradedb || airflow db upgrade` instead of `airflow initdb`
* Default to `pullPolicy: IfNotPresent` (to avoid DockerHub rate limits)
=> release 7.15.0

charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/ci/default-values.yaml, charts/airflow/files/pod_template.kubernetes-helm-yaml, charts/airflow/templates/_helpers/validate-values.tpl, charts/airflow/templates/config/configmap-pod-template.yaml, charts/airflow/templates/flower/flower-deployment.yaml, charts/airflow/templates/jobs/job-upgrade-db.yaml, charts/airflow/templates/scheduler/scheduler-deployment.yaml, charts/airflow/templates/webserver/webserver-deployment.yaml, charts/airflow/templates/worker/worker-statefulset.yaml, charts/airflow/values.yaml, ct-config.yaml
This release resolves some of the initial issues that have been uncovered with version `8.0.0`.
I have added a debug value called `helmWait`, which should be enabled when the `--wait` flag is used with `helm install`, to prevent it hanging forever. The reason we created a value for this, is most users are not using the `--wait` flag, and to prevent issues like #99 it is better that the `upgrade-db` job is removed before it is recreated (due to the immutability of Job specs)
- fixes #101
- fixes #99
- fixes #98
- fixes #97
=> release 8.0.1

charts/airflow/Chart.yaml, charts/airflow/templates/_helpers/pods.tpl
Signed-off-by: Burak Karakan <burak.karakan@gmail.com>
- fixes #113
This PR replaces the logs volume with the persistent volume claim. The fix here is recommended by @commandosss in #113, but I am not sure if it doesn't cause any other issues with the rest of the chart; I have created the PR to speed up the process in case this turns out to be the fix to the issue indeed.
=> fix volume definition for logs-data with existing claim

charts/airflow/Chart.yaml, charts/airflow/templates/jobs/job-create-connections.yaml, charts/airflow/templates/jobs/job-create-pools.yaml, charts/airflow/templates/jobs/job-create-users.yaml, charts/airflow/templates/jobs/job-create-variables.yaml, charts/airflow/templates/jobs/job-upgrade-db.yaml
Signed-off-by: Volodymyr Moseichuk <moskitone@gmail.com>
Jobs (helm-hooks) will run with the same serviceAccount as other pods.
=> run jobs with airflow serviceAccount

README.md, charts/airflow/Chart.yaml, charts/airflow/README.md
Some general docs updates:
- closes https://github.com/airflow-helm/charts/issues/207
- closes https://github.com/airflow-helm/charts/issues/184
=> release 8.1.3

charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/UPGRADE.md, charts/airflow/templates/_helpers/pods.tpl, charts/airflow/values.yaml
- fixes #157 
Add support for GIT_SYNC_MAX_FAILURES.
Signed-off-by: Nathan J. Mehl <n@oden.io>
=> Add support for GIT_SYNC_MAX_FAILURES

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Improve the GitHub issue templates.
=> improve github issue templates

charts/airflow/Chart.yaml, charts/airflow/examples/google-gke/custom-values.yaml
- fixes https://github.com/airflow-helm/charts/issues/224
copy an [old settings](https://github.com/airflow-helm/charts/blob/0f40ffe1c1/charts/airflow/values.yaml#L1018-L1025) in Airflow 1.10 era to V2
=> fix(example): hpa of gke example doesn't work

charts/airflow/CONTRIBUTING.md
=> docs: clarify CONTRIBUTING guide for adding values to README

charts/airflow/files/pod_template.kubernetes-helm-yaml, charts/airflow/templates/_helpers/pods.tpl, charts/airflow/templates/flower/flower-deployment.yaml, charts/airflow/templates/jobs/job-upgrade-db.yaml, charts/airflow/templates/scheduler/scheduler-deployment.yaml, charts/airflow/templates/webserver/webserver-deployment.yaml, charts/airflow/templates/worker/worker-statefulset.yaml
- fixes #254
- fixes #253
- fixes #245
=> fix: include volumeMounts in init-containers

charts/airflow/ci/default-values.yaml, charts/airflow/templates/jobs/job-upgrade-db.yaml, charts/airflow/values.yaml
- resolves #259
- fixes #230
- fixes #99
Implements changes described in issue: #259
=> refactor: remove `helmWait` value

charts/airflow/templates/_helpers/pods.tpl
- resolves #264
- fixes #196
Implements the changes described in #264
=> fix: mount `dags-data` with `readOnly=true` if `accessMode=ReadOnlyMany`

charts/airflow/templates/_helpers/validate-values.tpl
- resolves #262
- resolves #263
- Implements changes described in: 
- #262
- #263
=> feat: improve validation of `{logs, dags}.persistence.accessMode`

charts/airflow/templates/_helpers/pods.tpl
- fixes https://github.com/airflow-helm/charts/issues/258
- Implements the changes described in: https://github.com/airflow-helm/charts/issues/258
=> feat: wait for db-migrations when `airflow.legacyCommands=true`

charts/airflow/CHANGELOG.md
- resolves #273
- fixes #208
- #273
=> docs: fix the 8.0.0 upgrade guide for `dags.persistence`

charts/airflow/CHANGELOG.md, charts/airflow/Chart.lock, charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/requirements.yaml, charts/airflow/values.yaml
- resolves #278
- resolves #286
- Updates the chart version to `8.4.0`
- Implements changes described in:
- #278
- #286
=> chore: release 8.4.0

charts/airflow/templates/jobs/job-upgrade-db.yaml, charts/airflow/templates/sync/sync-connections-job.yaml, charts/airflow/templates/sync/sync-pools-job.yaml, charts/airflow/templates/sync/sync-users-job.yaml, charts/airflow/templates/sync/sync-variables-job.yaml
- resolves https://github.com/airflow-helm/charts/issues/297
- Ensures systems that run `helm template ...` (like argo-cd) will not run into Job immutability errors.
- https://github.com/airflow-helm/charts/issues/297
=> fix: remove Job dependency on `.Release.Revision`

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml
- N/A
- Updates the chart version to 8.4.1
=> chore: release 8.4.1

charts/airflow/templates/sync/_helpers/sync_users.tpl
- resolves: https://github.com/airflow-helm/charts/issues/316
- https://github.com/airflow-helm/charts/issues/316
=> fix: ensure sync_users.py closes db connections after each loop

charts/airflow/templates/_helpers/validate-values.tpl
- resolves https://github.com/airflow-helm/charts/issues/291
- https://github.com/airflow-helm/charts/issues/291
=> feat: add validation for `externalDatabase.type`

charts/airflow/templates/sync/sync-connections-deployment.yaml, charts/airflow/templates/sync/sync-connections-job.yaml, charts/airflow/templates/sync/sync-pools-deployment.yaml, charts/airflow/templates/sync/sync-pools-job.yaml, charts/airflow/templates/sync/sync-users-deployment.yaml, charts/airflow/templates/sync/sync-users-job.yaml, charts/airflow/templates/sync/sync-variables-deployment.yaml, charts/airflow/templates/sync/sync-variables-job.yaml
- fixes https://github.com/airflow-helm/charts/issues/310
- closes https://github.com/airflow-helm/charts/pull/311 (superseded by this PR)
- Makes it so that `airflow.extraPipPackages` is installed in the snyc Jobs/Deployments (for `airflow.{users,connections,...}`)
=> feat: install `airflow.extraPipPackages` in snyc Jobs/Deployments

charts/airflow/templates/config/secret-config.yaml
- fixes https://github.com/airflow-helm/charts/issues/353
- Use the `data` field (rather than`stringData`) to specify Secret keys which may be removed, this is needed because of:  https://github.com/helm/helm/issues/10010
=> fix: set removable secret keys with `data` field not `stringData`

charts/airflow/templates/NOTES.txt
- resolves https://github.com/airflow-helm/charts/issues/333
- Rewrites the post-install NOTES.txt which are presented to the user after each `helm install/upgrade ...`
- Adds many WARNINGS which will display in NOTES if the user needs to be aware of something
=> feat: improve post-install NOTES.txt

charts/airflow/templates/_helpers/pods.tpl
- resolves https://github.com/airflow-helm/charts/issues/376
- fixes https://github.com/airflow-helm/charts/issues/180
- Includes `airflow.config` and `airflow.extraEnv` in the git-sync containers
=> feat: include `airflow.{config,extraEnv}` in git-sync container

charts/airflow/CHANGELOG.md, charts/airflow/templates/flower/flower-deployment.yaml
- resolves https://github.com/airflow-helm/charts/issues/377
- Includes `airflow.extraContainers` in the flower Deployment
=> feat: include `airflow.extraContainers` in flower Deployment

charts/airflow/README.md, charts/airflow/templates/_helpers/validate-values.tpl, charts/airflow/templates/flower/flower-ingress-v1beta1.yaml, charts/airflow/templates/webserver/webserver-ingress-v1beta1.yaml, charts/airflow/values.yaml
- resolves https://github.com/airflow-helm/charts/issues/378
- https://github.com/airflow-helm/charts/issues/378
- Adds the following values:
- `ingress.apiVersion` (default: `networking.k8s.io/v1`)
=> feat: use `networking.k8s.io/v1` Ingress by default

charts/airflow/README.md, charts/airflow/files/pod_template.kubernetes-helm-yaml, charts/airflow/templates/_helpers/pods.tpl, charts/airflow/templates/flower/flower-deployment.yaml, charts/airflow/templates/scheduler/scheduler-deployment.yaml, charts/airflow/templates/sync/sync-connections-deployment.yaml, charts/airflow/templates/sync/sync-connections-job.yaml, charts/airflow/templates/sync/sync-pools-deployment.yaml, charts/airflow/templates/sync/sync-pools-job.yaml, charts/airflow/templates/sync/sync-users-deployment.yaml, charts/airflow/templates/sync/sync-users-job.yaml, charts/airflow/templates/sync/sync-variables-deployment.yaml, charts/airflow/templates/sync/sync-variables-job.yaml, charts/airflow/templates/webserver/webserver-deployment.yaml, charts/airflow/templates/worker/worker-statefulset.yaml, charts/airflow/values.yaml
- resolves https://github.com/airflow-helm/charts/issues/296
- https://github.com/airflow-helm/charts/issues/296
- Adds the following values: 
- `airflow.defaultSecurityContext` (default: `{fsGroup: 0}`)
=> feat: add `airflow.defaultSecurityContext` value

charts/airflow/README.md, charts/airflow/files/pod_template.kubernetes-helm-yaml, charts/airflow/templates/_helpers/pods.tpl, charts/airflow/templates/scheduler/scheduler-deployment.yaml, charts/airflow/templates/sync/sync-connections-deployment.yaml, charts/airflow/templates/sync/sync-connections-job.yaml, charts/airflow/templates/sync/sync-pools-deployment.yaml, charts/airflow/templates/sync/sync-pools-job.yaml, charts/airflow/templates/sync/sync-users-deployment.yaml, charts/airflow/templates/sync/sync-users-job.yaml, charts/airflow/templates/sync/sync-variables-deployment.yaml, charts/airflow/templates/sync/sync-variables-job.yaml, charts/airflow/templates/webserver/webserver-deployment.yaml, charts/airflow/templates/worker/worker-statefulset.yaml, charts/airflow/values.yaml
- resolves https://github.com/airflow-helm/charts/issues/313
- fixes https://github.com/airflow-helm/charts/issues/312
- https://github.com/airflow-helm/charts/issues/313
- Adds the following values:
- `airflow.defaultNodeSelector`
- `airflow.defaultAffinity`
- `airflow.defaultTolerations`
=> feat: add `airflow.{defaultNodeSelector,defaultAffinity,defaultTolerations}` values

charts/airflow/README.md, charts/airflow/templates/NOTES.txt, charts/airflow/values.yaml
- N/A
- Significantly cleans up the docstrings & examples in `values.yaml`
- Improves the WARNING message if the user enables `extraPipPackages`
=> docs: general cleanup

charts/airflow/README.md, charts/airflow/templates/_helpers/pods.tpl, charts/airflow/templates/config/secret-local-settings.yaml, charts/airflow/templates/flower/flower-deployment.yaml, charts/airflow/templates/scheduler/scheduler-deployment.yaml, charts/airflow/templates/sync/sync-connections-deployment.yaml, charts/airflow/templates/sync/sync-connections-job.yaml, charts/airflow/templates/sync/sync-pools-deployment.yaml, charts/airflow/templates/sync/sync-pools-job.yaml, charts/airflow/templates/sync/sync-users-deployment.yaml, charts/airflow/templates/sync/sync-users-job.yaml, charts/airflow/templates/sync/sync-variables-deployment.yaml, charts/airflow/templates/sync/sync-variables-job.yaml, charts/airflow/templates/webserver/webserver-deployment.yaml, charts/airflow/templates/worker/worker-statefulset.yaml, charts/airflow/values.yaml
- resolves https://github.com/airflow-helm/charts/issues/373
- fixes https://github.com/airflow-helm/charts/issues/371
- Impelentes the changes described in:
- https://github.com/airflow-helm/charts/issues/373
- Adds the following new values:
- `airflow.localSettings`:
- `airflow.localSettings.stringOverride`
- `airflow.localSettings.existingSecret`
=> feat: add `airflow.localSettings.*` values

charts/airflow/README.md
-  N/A
- Cleans up the top section of the README
=> docs: cleanup readme

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml
- N/A
- Releases chart version `8.5.1`
=> chore: release 8.5.1

charts/airflow/templates/config/secret-config-envs.yaml
- resolves https://github.com/airflow-helm/charts/issues/318
- fixes https://github.com/airflow-helm/charts/issues/401
- fixes https://github.com/airflow-helm/charts/issues/394
- fixes https://github.com/airflow-helm/charts/issues/213
- Apply URL encoding to `DATABASE_USER` so that unsafe characters do not corrupt the connection string (especially `@`).
- Implements changes described in:
- https://github.com/airflow-helm/charts/issues/318
=> feat: url encode DATABASE_USER in connection strings

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml
- N/A
- Releases chart version `8.8.2`
=> chore: release 8.5.2

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml, charts/airflow/values.yaml
- https://github.com/airflow-helm/charts/milestone/1
- Releases chart version `8.5.3`
=> chore: release 8.5.3

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml, charts/airflow/README.md
- N/A
- Release version `8.6.1` of the chart
=> chore: release 8.6.1

charts/airflow/README.md
Add `2.4` as one of the supported versions in the link
=> docs: add `2.4` to supported versions

charts/airflow/templates/_helpers/validate-values.tpl
- fixed typo in `validate-values.tpl` error message
=> fix: typo in error message

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/docs/faq/configuration/airflow-plugins.md, charts/airflow/docs/faq/configuration/extra-python-packages.md, charts/airflow/docs/faq/dags/load-dag-definitions.md, charts/airflow/examples/google-gke/custom-values.yaml, charts/airflow/examples/minikube/custom-values.yaml, charts/airflow/sample-values-CeleryExecutor.yaml, charts/airflow/sample-values-CeleryKubernetesExecutor.yaml, charts/airflow/sample-values-KubernetesExecutor.yaml, charts/airflow/values.yaml
- fixes #704
- releases version `8.7.0` of the chart
- updates default images:
- airflow: `apache/airflow:2.5.3-python3.8`
- git-sync: `registry.k8s.io/git-sync/git-sync:v3.6.5`
- Postgres: `ghcr.io/airflow-helm/postgresql-bitnami:11.16-patch.0`
- Redis: `bitnami/redis:5.0.14-debian-10-r173`
=> chore: release 8.7.0

charts/airflow/docs/faq/dags/airflow-connections.md, charts/airflow/docs/faq/monitoring/log-persistence.md
fixes typo in doc, wabs -> wasb
=> docs: fix typo for "wasb"

charts/airflow/docs/faq/dags/airflow-connections.md
- fixes #732
- 404 not found url changed
=> docs: fix external secrets website links

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/docs/guides/quickstart.md, charts/airflow/docs/guides/upgrade.md
- N/A
- releases version `8.7.1` of the chart
=> chore: release 8.7.1

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/docs/faq/configuration/airflow-plugins.md, charts/airflow/docs/faq/configuration/extra-python-packages.md, charts/airflow/docs/faq/dags/load-dag-definitions.md, charts/airflow/examples/google-gke/custom-values.yaml, charts/airflow/examples/minikube/custom-values.yaml, charts/airflow/sample-values-CeleryExecutor.yaml, charts/airflow/sample-values-CeleryKubernetesExecutor.yaml, charts/airflow/sample-values-KubernetesExecutor.yaml, charts/airflow/values.yaml
- N/A
- releases version `8.8.0` of the chart
=> chore: release 8.8.0

.github/workflows/_release-image.yaml, .github/workflows/_test-image.yaml, .github/workflows/charts--release.yaml, .github/workflows/charts--run-tests.yaml, .github/workflows/sync-readme.yaml
This PR updates to the latest versions of most github actions, mainly so we don't get broken by the deprecation of older versions of NodeJS.
We also updated the Kind testing cluster to `v1.27.11` and helm to `v3.13.3`.
=> ci: update github actions

charts/airflow/CHANGELOG.md, charts/airflow/Chart.yaml, charts/airflow/README.md, charts/airflow/docs/faq/configuration/airflow-plugins.md, charts/airflow/docs/faq/configuration/extra-python-packages.md, charts/airflow/docs/faq/dags/load-dag-definitions.md, charts/airflow/docs/faq/kubernetes/affinity-node-selectors-tolerations.md, charts/airflow/docs/faq/kubernetes/mount-environment-variables.md, charts/airflow/docs/faq/kubernetes/mount-files.md, charts/airflow/docs/faq/monitoring/log-persistence.md, charts/airflow/examples/google-gke/custom-values.yaml, charts/airflow/examples/minikube/custom-values.yaml, charts/airflow/sample-values-CeleryExecutor.yaml, charts/airflow/sample-values-CeleryKubernetesExecutor.yaml, charts/airflow/sample-values-KubernetesExecutor.yaml, charts/airflow/values.yaml
-  Milestone: https://github.com/airflow-helm/charts/milestone/11
- releases version `8.9.0` of the chart
=> chore: release 8.9.0
